cursor #e7e0e8
cursor_text_color #cbc4cf

foreground            #e7e0e8
background            #141218
selection_foreground  #332d41
selection_background  #ccc2db
url_color             #d1bcfd

color0   #141218
color1   #ff728e
color2   #7efd99
color3   #ffda72
color4   #bea6f0
color5   #4f3d75
color6   #d1bcfd
color7   #f4efff
color8   #9c98a4
color9   #ff9fb2
color10  #a5ffb8
color11  #ffe7a5
color12  #d9c7ff
color13  #dfd1ff
color14  #ebe1ff
color15  #faf8ff
