[colors.primary]
background = '#141218'
foreground = '#e7e0e8'

[colors.selection]
text = '#e7e0e8'
background = '#4e3d75'

[colors.cursor]
text = '#141218'
cursor = '#d1bcfd'

[colors.normal]
black   = '#141218'
red     = '#ff728e'
green   = '#7efd99'
yellow  = '#ffda72'
blue    = '#bea6f0'
magenta = '#4f3d75'
cyan    = '#d1bcfd'
white   = '#f4efff'

[colors.bright]
black   = '#9c98a4'
red     = '#ff9fb2'
green   = '#a5ffb8'
yellow  = '#ffe7a5'
blue    = '#d9c7ff'
magenta = '#dfd1ff'
cyan    = '#ebe1ff'
white   = '#faf8ff'
